# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bff72ceab61d39f5b7207704a2915c80b441e9ba864795912149136af7e54a0130d9b1418d0aea159921816e4752d32fed662d4656bd1f2930caf86487e2c0d8

test:
  secret_key_base: 7abc0556c2b4ae73b647c3e9b11f6747fb38f3520bda663afe33432d3ffd3878199a5fd002f7284ca5431bcf623174a7e70a3a53b1306ccaf8cdbaf2312a556d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
